ansible-ThoTeam/nexus3-oss

defaults/main.yml, files/groovy/create_task.groovy, files/groovy/setup_email.groovy, tasks/main.yml, tasks/nexus_install.yml
Reworked original pull request from @dannyk81 on original repository.
This is part of operations needed to hard-fork hard fork of https://github.com/savoirfairelinux/ansible-nexus3-oss
=> Feature config email from @Dannyk81

defaults/main.yml, files/groovy/create_repo_nuget_group.groovy, files/groovy/create_repo_nuget_hosted.groovy, files/groovy/create_repo_nuget_proxy.groovy, tasks/create_repo_nuget_group_each.yml, tasks/create_repo_nuget_hosted_each.yml, tasks/create_repo_nuget_proxy_each.yml, tasks/main.yml, tasks/nexus_install.yml, vars/blob_vars.yml
=> Add nuget support from @AirsickPayload

.travis.yml, defaults/main.yml, files/groovy/create_repo_pypi_proxy.groovy, files/groovy/create_repo_raw_proxy.groovy, pom.xml, tests/run_all_tests.sh, tests/syntaxChecking.groovy, tests/test_groovySyntax.sh
When fixing the groovy scripts to fix bugs regarding non persistent changes to repo for reprovionning, some syntax errors were introduced in some script.
This PR aims to:
- Setup groovy syntax checking on travis so that we can monitor this on a continuous basis
- Fix the errors that were introduced
=> Fix groovy syntax errors

.yamllint, defaults/main.yml, meta/main.yml, molecule/default/molecule.yml, molecule/default/playbook.yml, tasks/declare_script_each.yml, tasks/main.yml, tasks/nexus_install.yml, tasks/nexus_purge.yml, vars/blob_vars.yml
=> Fix obey yamllint

molecule/default/molecule.yml, tasks/nexus_install.yml
=> Add a check in our molecule test sequence

README.md, defaults/main.yml, files/groovy/create_repo_yum_proxy.groovy, molecule/default/playbook.yml, tasks/create_repo_yum_proxy_each.yml, tasks/main.yml, vars/blob_vars.yml
Add support for configuring yum proxy repositories in nexus.
Implementation for #9
=> Yum proxy support (Implementation for #9)

defaults/main.yml
=> Bump nexus version to 3.6.2-01

files/groovy/create_repo_nuget_hosted.groovy, molecule/default/playbook.yml, tasks/main.yml
=> Fix delete default yum blobstore

README.md, defaults/main.yml
- Update doc
- Bump default nexus version to 3.7.0-04
=> Finalize release2.0

.travis.yml, README.md, molecule/selinux/playbook.yml, tasks/nexus-restore.yml, templates/backup.groovy.j2, templates/nexus-blob-restore.sh.j2
Fixes #19 
Allow backups to be ran scheduled or manually from nexus GUI as many time as wanted by the user
=> Unrestricted backups

README.md, defaults/main.yml, templates/backup.groovy.j2
Implementation for #32.
Fixes #32
=> Backup rotation implementation

defaults/main.yml, tasks/call_script.yml, tasks/declare_script_each.yml, tasks/nexus_install.yml
Implement new API endpoints for nexus 3.8
Fixes #14
=> Rest API endpoint changed for nexus 3.8.0

README.md
=> Add reference to mod_proxy_http in documentation

README.md
=> Document molecule selinux scenario

README.md
Fixes #49 
+ sparse doc for other security realms
=> Docfix required ldap security realm for ldap connections

.travis.yml, CODE_OF_CONDUCT.md, README.md, defaults/main.yml, files/groovy/create_task.groovy, molecule/selinux/playbook.yml, tasks/call_script.yml, tasks/declare_script_each.yml, tasks/nexus-restore.yml, tasks/nexus_install.yml, templates/backup.groovy.j2, templates/nexus-blob-restore.sh.j2
Move all new dev features on master for 2.1 release
=> Prepare 2.1 release

README.md, defaults/main.yml, files/groovy/create_repo_yum_hosted.groovy, molecule/default/playbook.yml, molecule/nexus_test_vars.yml, molecule/selinux/molecule.yml, molecule/selinux/playbook.yml, pom.xml, tasks/create_repo_yum_hosted_each.yml, tasks/main.yml
This is new in nexus 3.8.
Added some enhancement to molecule scenario to ease dev/tests.
=> Add support for yum hosted repositories

README.md, defaults/main.yml, pom.xml
Update to latest nexus version
=> Bump nexus version to 3.9.0

README.md, molecule/default/molecule.yml
=> Add travis tests for Ubuntu Bionic (18.04)

README.md, molecule/default/molecule.yml
=> Add molecule tests for debian jessie

defaults/main.yml, files/groovy/create_repo_yum_group.groovy, molecule/nexus_test_vars.yml, tasks/create_repo_yum_group_each.yml, tasks/main.yml
=> Implement yum group support

README.md, defaults/main.yml, files/groovy/create_blobstore.groovy, tasks/create_blobstore_each.yml
This is a rebase/rework of #93 to include to next release.
Implementation for #87
=> S3 Blobstore automation

README.md, files/groovy/create_repo_bower_proxy.groovy, files/groovy/create_repo_docker_proxy.groovy, files/groovy/create_repo_maven_proxy.groovy, files/groovy/create_repo_npm_proxy.groovy, files/groovy/create_repo_nuget_proxy.groovy, files/groovy/create_repo_pypi_proxy.groovy, files/groovy/create_repo_raw_proxy.groovy, files/groovy/create_repo_rubygems_proxy.groovy, files/groovy/create_repo_yum_proxy.groovy
This is a rebase/rework of #95 to include to next release.
Notable changes with original PR:
- Added negative cache handling for docker proxies
- Added a brief documentation
=> Negative cache handling for proxy repositories

README.md, defaults/main.yml, tasks/nexus_install.yml
Implementation for #97
Allow to set JVM memory config from variables:
- min heap size
- max heap size
- max direct memory
=> Nexus JVM memory configuration

molecule/selinux/prepare.yml, tasks/selinux-RedHat.yml
with_items/loop is not a good solution to send packages for yum. Sending lists in the name variable is much more efficient.
See notes for module yum: https://docs.ansible.com/ansible/latest/modules/yum_module.html#notes
=> Send lists to yum. Don't use with_items

molecule/sync-nexus-package.yml, tasks/nexus_install.yml
Some events were not taken correctly into account to trigger a nexus restart
Fixes #98
=> Make sure nexus is restarted on several config/upgrade changes

README.md, defaults/main.yml, files/groovy/create_repo_bower_proxy.groovy, files/groovy/create_repo_docker_proxy.groovy, files/groovy/create_repo_maven_proxy.groovy, files/groovy/create_repo_npm_proxy.groovy, files/groovy/create_repo_nuget_proxy.groovy, files/groovy/create_repo_pypi_proxy.groovy, files/groovy/create_repo_raw_proxy.groovy, files/groovy/create_repo_rubygems_proxy.groovy, files/groovy/create_repo_yum_proxy.groovy, molecule/nexus_test_vars.yml
=> Handle cache refresh config for proxy repos

tasks/nexus_install.yml
This is a rebase of #90 on latest master.
=> Overcome aggressive umask

tasks/check_deprecated.yml, tasks/main.yml, tasks/nexus_install.yml
- Move existing deprecation checks to a specific file
- Add deprecation check for nexus_purge var refactoring (Part of #111 PR)
=> Deprecation checks

README.md, defaults/main.yml, files/groovy/create_blobstore.groovy, files/groovy/setup_privilege.groovy, files/groovy/setup_role.groovy, files/groovy/setup_user.groovy, templates/backup.groovy.j2
- Modify backup script for schedule task to use standard nexus log
- Add some loging for some groovy scripts (to be contiued...)
=> Groovy scripts should log to nexus log

.gitignore, README.md, molecule/default-playbook.yml, tasks/nexus_install.yml
=> Update nexus on demand

README.md, defaults/main.yml, tasks/nexus_install.yml
Hi
Fixing the bug #129 
Could you merge? thanks
nicolas
=> parameterising home directory for nexus os user

.yamllint, README.md, defaults/main.yml, molecule/sync-nexus-package.yml, tasks/call_script.yml, tasks/declare_script_each.yml, tasks/main.yml, tasks/nexus_install.yml, templates/nexus-blob-restore.sh.j2
* E602: Don't compare to empty string
* E204: Lines should be no longer than 120 chars
* E504: Use 'connection: local' or 'delegate_to: localhost' instead of 'local_action'
* E206: Variables should have spaces after {{ and before }}
=> Enhancements following galaxy code score gidelines

README.md, defaults/main.yml, tasks/httpd_reverse_proxy_config.yml, templates/nexus-vhost.conf
=> Allow configuration of SSL cert chain file

README.md, defaults/main.yml, files/groovy/setup_ldap_user.groovy, tasks/main.yml, tasks/setup_ldap_user_each.yml
This is a rebase/rework of #135
=> LDAP Users Role Mappings

README.md, tasks/nexus_install.yml
=> Fail with info message on rsync error

handlers/main.yml
=> Allow deployment of nexus PRO

README.md, defaults/main.yml, molecule/nexus_test_vars.yml, tasks/call_script.yml, tasks/check_deprecated.yml, tasks/declare_script_each.yml, tasks/main.yml, tasks/nexus_install.yml, templates/nexus-vhost.conf
=> Allow to customize api uri/scheme for provisionning

README.md, files/groovy/setup_privilege.groovy, molecule/nexus_test_vars.yml
This is a rebase/rework of #124
=> Extend privileges properties.

README.md, files/groovy/create_repos_from_list.groovy, tasks/main.yml
Implementation for #152.
Will also embark doc changes from #149
=> http proxy must be configured before blob stores for S3

tasks/main.yml, tasks/requirements_and_deprecated.yml
This was an occasion to move all requirements and deprecation checks that can be run at role start in the same file
=> Add a requirement check for jmespath

README.md, defaults/main.yml, templates/nexus-vhost.conf
... and fix documentation on different existing vars
This is an implementation for #157
=> Fix multiple ServerName directives for ssl reverse proxy.

requirements.txt, tasks/httpd_reverse_proxy_config.yml, tasks/main.yml, tasks/nexus_install.yml, templates/nexus-vhost.conf
Fix failing testinfra test
Fix deprecation warnings
=> ansible 2.8 compatibility

README.md, defaults/main.yml
=> Specific default tmp for redhat.

README.md, defaults/main.yml, tasks/nexus_install.yml
This is a rebase of #201 with documentation added
=> Configure nexus listening IP (application-host)

tasks/nexus_install.yml
Add check for admin.password before trying to read it from disk.
Fixes #194
=> Add check admin.password file exists

files/groovy/setup_email.groovy
=> email set up by class instead of the interface

files/groovy/setup_ldap.groovy, pom.xml
Using LdapConfigurationManager to get ldapConfig
Fixes #224
=> fixed ldap groovy

files/groovy/create_cleanup_policies_from_list.groovy
Script breaks in nexus 3.20. Fix that.
Fixes #230
=> Fix groovy script for cleanup policies

templates/nexus-blob-restore.sh.j2
=> blob restore loop over names

files/groovy/create_content_selector.groovy
=> Backward compatibility for content selectors

tasks/main.yml
=> Get blob list from var, not statically

defaults/main.yml, tasks/process_repos_list.yml, vars/blob_vars.yml
This PR adds support for configuring helm repositories
Fixes #283
=> Add support for helm repositories.

.travis.yml, README.md, defaults/main.yml, molecule/nexus_common_test_vars.yml, tasks/process_repos_list.yml, vars/blob_vars.yml
=> Rebase and rework of #274 for merge

README.md, defaults/main.yml, molecule/nexus_common_test_vars.yml, tasks/process_repos_list.yml, vars/blob_vars.yml
This PR adds support for configuration of conda (proxy) repositories.
=> support conda repositories

README.md, defaults/main.yml, molecule/nexus_common_test_vars.yml, tasks/process_repos_list.yml, vars/blob_vars.yml
This enables the creation of golang repos
=> Add support for go repos

tasks/nexus_install.yml
=> Fix Nexus upgrades with plugins

tasks/main.yml, tasks/nexus_install.yml
This is a re-implementation of #324 (which has been closed) with missing conditions in the main task file
Fixes #323
=> Check empty data dir with platform independant find module

handlers/main.yml, tasks/nexus_install.yml
=> Fix running systemd service in selinux

README.md, files/groovy/create_repos_from_list.groovy, molecule/nexus_common_test_vars.yml
=> Add ability to set auto block and HTTP settings for proxy repos

tasks/nexus_install.yml
Missing / in karaf log definit for nexus.vmoption
Fixes #375
=> Fix karaf log path
