molecule/default/molecule.yml, tasks/nexus_install.yml, tasks/nexus_purge.yml
At time being, this role is not idempotent. i.e. running the role several times without any changes to role files still reports changes in ansible. As a good practice, this should be fixed.
We should work out on:
1- Setup idempotency tests in molecule
2- Fix the tasks reporting changes when they should not and/or modifiy the role works so that it does not fire unnecessary tasks when they are not needed.
=> Make the role idempotent

README.md, defaults/main.yml, files/groovy/create_task.groovy, molecule/default/playbook.yml
Task configuration only takes into account string properties. This PR allows to set boolean properties as well.
=> Allow configuration of boolean properties in nexus scheduled tasks

.travis.yml, handlers/main.yml, molecule/.nexus-downloads/.gitignore, molecule/default/create.yml, molecule/default/molecule.yml, molecule/default/prepare.yml, molecule/selinux/molecule.yml, molecule/selinux/prepare.yml, molecule/sync-nexus-package.yml
The role announces requirements for ansible>=2.2.
no_block attribute for systemd is only available for ansible 2.3 and above
Stick to the announced requirements.
This PR also refactored molecule test to gain time in local testing by sharing nexus downloads accros scenarios.
=> Attribute no_block for systemd is not available in ansible 2.2

files/groovy/create_task.groovy
Fixes https://github.com/ansible-ThoTeam/nexus3-oss/issues/33
* Exisiting tasks are updated and not deleted first
* Using `parsed_args.booleanTaskProperties.each` from v2.0
* In case the task being updated is currently running, log the issue and continue (instead of throwing an exception)
=> Tasks modify without delete

.gitignore, molecule/default/molecule.yml, molecule/default/playbook.yml, molecule/default/tests/test_default.py, molecule/selinux/playbook.yml, templates/nexus-vhost.conf
This is a rework of original PR #54 with a simpler implementation and tests.
=> Apache needs AllowEncodedSlashes to download npm scoped packages

tasks/nexus_install.yml
cf. issue https://github.com/ansible-ThoTeam/nexus3-oss/issues/58
Enable option `use_ssh_args` of `synchronize` module is needed to load ssh arguments.
=> chore: add `use_ssh_args` option to sync scripts task

README.md, molecule/default/molecule.yml
For maintenance reasons (i.e. problems importing the docker project in my ide correctly), the github and docker hub repositories for unbunt test image have been renamed:
ansible-ubuntu16.04-apache-java => ansible-ubuntu16_04-apache-java
=> Switch ubuntu docker test image to new path after renaming

README.md, defaults/main.yml, molecule/nexus_test_vars.yml, tasks/main.yml
Allows the Remote User Token auth realm to be configured by adding the capability with the httpHeader parameter.
This is a simple clean rebased rework of #68
=> Rut Auth Header Capability

README.md, defaults/main.yml, molecule/sync-nexus-package.yml, tasks/nexus_install.yml
By default, the default site is used. But now this can be overridden if needed (e.g. in closed environments).
=> Add variable for specifying the Nexus package download URL.

tasks/nexus_install.yml, templates/nexus-blob-restore.sh.j2
Restore directory for db changed name in nexus 3.11
<nexus_data_dir>/backup => <nexus_data_dir>/restore-from-backup
=> Fix database restore path changed in nexus 3.11

README.md, defaults/main.yml, molecule/sync-nexus-package.yml, tasks/nexus_install.yml, tasks/nexus_purge.yml
Detect the latest available nexus by analyzing the redirect url
when calling https://download.sonatype.com/nexus/3/latest-unix.tar.gz
Fixes #76
=> Install latest nexus version by default

README.md, defaults/main.yml, files/groovy/create_repo_bower_proxy.groovy, files/groovy/create_repo_docker_proxy.groovy, files/groovy/create_repo_maven_proxy.groovy, files/groovy/create_repo_npm_proxy.groovy, files/groovy/create_repo_nuget_proxy.groovy, files/groovy/create_repo_pypi_proxy.groovy, files/groovy/create_repo_raw_proxy.groovy, files/groovy/create_repo_rubygems_proxy.groovy, files/groovy/create_repo_yum_proxy.groovy, molecule/nexus_test_vars.yml
Negative cache implementation (#100) introduced some new variables which names don't respect the de facto coding standard (lower case with underscore separator).
Moreover, documentation and default vars were not updated correctly/accordingly.
This PR fixes those issues.
=> Fix Negative cache implementation

README.md, defaults/main.yml, files/groovy/setup_capability.groovy, molecule/nexus_test_vars.yml, tasks/main.yml
Auditing capability is created by default but disabled. Allow to turn it on.
This requires a change to how capabilities are handled through groovy script files/groovy/setup_capability.groovy
Before: if capability exists, use its current value for "This capability is enabled"
After: if capability exists, enable it by default unless an arg `capability_enabled: false' is passed
=> Allow to configure nexus auditing capability

README.md, defaults/main.yml, tasks/main.yml, tasks/nexus_install.yml
This is a maintenance/debug command. Allow to force groovy resgistration with a special var (rather than having to manually delete the reference directory on target machine).
Took this opportunity to document this and also the purge procedure for nexus and renamed the variable for purge to follow var naming standards.
purge=true must now be nexus_purge=true
=> Allow to force groovy scripts (re-)registration

README.md, defaults/main.yml, templates/backup.groovy.j2
Backups where systematically rotated after current backup is performed.
This is still the default but you can now choose to rotate before performing current backup.
=> Allow to configure pre or post backup rotation

.gitignore, tasks/nexus_install.yml
Some connection plugins like lxd are not supported by the synchronize module. On the other hand uploading a lot of files with the copy module is really slow. 
This PR replaced the synchronize modul with archive/unarchive to upload the script files fast and in a way it is supported for more connection plugins.
=> Allow to use this role with lxd connection plugin

tasks/nexus_install.yml
Whatever the current settings are (global become activated or not) a local action does not require escalation privileges.
=> Disable sudo for local action

files/groovy/delete_repo.groovy
Hello,
When we're trying to delete a repository that doesn't exist anymore an exception is raised by nexus, to avoid that I'm checking the repository exist before deleting it.
Also doing a destroy on the repository, I've seen some error in the UI only doing the delete.
Is it ok for you to integrate it ?
Regards,
=> Avoid exception when trying to remove a repository that doesn't exist

README.md
I've used this role in many projects, and had to find the correct `nexus_version`, by googling.
To make things easier for everyone, I updated the README to point to the correct archive link where all Nexus 3 versions are visible.
=> nexus_version link update in README

README.md, defaults/main.yml, tasks/nexus_install.yml
Handy as a debug parameter whatever install scenario we are facing (check, upgrade, first install...)
Can be used later in subsequent tasks if needed (e.g. for upgrade email notifications)
=> Register running version in nexus_version_running

requirements.txt
- Go back to stock molecule version on pypi now that
development is back on tracks
- Add yamllint as it has been dropped from molecule deps
- Move to docker instead of docker-py which is deprecated
=> Rework requirements.txt to fix ci builds failling (yamllint not found)

.flake8, files/groovy/create_repos_from_list.groovy, filter_plugins/nexus3_oss_filters.py, tasks/call_script.yml, tasks/main.yml
This is an other implementation for #158.
Since groovy script refactoring has started, new scripts should now report the details of their execution. `tasks/call_script.yml` is not yet aware of these changes. This causes a situation where the script can report an error in its json return while the global http requests status still is 200, which will cause the error to be ignored silently. This is exactly what has been reported in #158.
This PR introduces a custom class with three filters able to check the script return and make the difference between old scripts (without details) and new ones (containing a json result with changed, error and details). For old script, only the http status is taken into account. For new scripts the detailed result is taken into account. …
=> Privileges defaults are not applied and create privileges fails silently

files/groovy/setup_users_from_list.groovy, tasks/nexus_install.yml
* Default admin password is now generated on first install and written to a file in nexus data dir. This breaks the admin password detection/change.
* An unnecessary `@Field` transform in script `setup_users_from_list.groovy` causes the script to Fail with the new version.
Fixes #174, #175
=> Fix broken build with nexus 3.17

README.md, defaults/main.yml, files/groovy/setup_ldap.groovy, tasks/setup_ldap_each.yml
Allow to define if ldap implementation should use the internal nexus trust store or not (default).
Fixes #178
=> Add the use_trust_store setting to ldap config

defaults/main.yml
Previous default settings:
Min Heap: 1200M
Max Heap: 1200M
Direct Memory: 2G
New defaults:
Min Heap: 2703M
Max Heap: 2703M
Direct Memory: 2703M
See https://issues.sonatype.org/browse/NEXUS-19954
=> Update default RAM settings according to 2.18 release

files/groovy/create_blobstores_from_list.groovy
This is an implementation to fix #160.
The problem is in groovy script `files/groovy/create_blobstores_from_list.groovy`
When catching an exception on blobstore creation we do not define the var `msg` which is later used in a `log.info` function. This PR reworks `msg` definition and loging so that this error is not present anymore
=> S3 blobstore creation fails with error `No such property: msg for class: Script5`

files/groovy/create_repos_from_list.groovy
Repositories are not updated after creation on subsequent role run. This is due to a buggy condition checking if any configuration changed. See commit and changes for details.
Fixes #186
=> Fix update condition for repositories

defaults/main.yml, files/groovy/create_repos_from_list.groovy
Add [Foreign Layers](https://help.sonatype.com/repomanager3/formats/docker-registry/foreign-layers) support for docker-proxy repos in Nexus 3.19.
Fixes #195
=> Add foreign layers support

.travis.yml, requirements.txt
The build is apparently broken due to a ci problem while installing python dependencies. Ongoing inquiry.
=> Ongoing test for currently failing ci build

README.md
In the README.md documentation, the example to play the role references a wrong name: `ansible-ThoTeam.nexus3-oss`
The correct name as found on galaxy is : `ansible-thoteam.nexus3-oss` (without capitalization)
=> Role name in documentation does not reflect real one.

molecule/nexus_common_test_vars.yml, tasks/main.yml
Nexus 3.19 fails if you use roles containing repo privileges if those repos are not created first.
Reimplementation of #210 with a test for molecule
=> Create privileges, users and roles after repos

README.md, tasks/nexus_install.yml
Allow to disable SSL certificate verification when downloading
nexus package.
Fixes #184
=> Nexus download SSL verification switch

molecule/default-centos7/molecule.yml, molecule/default-debian_buster/molecule.yml, molecule/default-debian_stretch/molecule.yml, molecule/default-ubuntu_16.04/molecule.yml, molecule/default-ubuntu_18.04/molecule.yml, molecule/default/molecule.yml, molecule/selinux/molecule.yml
This is redundant and missleading (i.e. when you copy of move a scenario
for example). The default name is the name of the containing folder
which should be more than enough. Moreover, this feature will probably
be deprecated in future releases for performace sake:
https://github.com/ansible/molecule/issues/2434
=> Remove redundant scenario names in molecule.yml

README.md, files/groovy/create_task.groovy, molecule/nexus_common_test_vars.yml, pom.xml
This is a rebase + Fixes and documentation for #173
+ additions from #183 (monthly and weekly schedule)
* Add a new `schedule_type` param for tasks which defaults to "cron".
* Add a new params to support schedule types.
* Adding CI tests and documentation.
=> Add more schecule options for tasks

README.md, defaults/main.yml, tasks/nexus_install.yml
Add `{{ nexus_onboarding_wizard }}` var to control whether the onboarding wizard shows on first admin login (default `nexus_onboarding_wizard: false`) for Nexus version >= 3.17.0
Fixes #192
=> Add logic to control the Nexus Onboarding Wizard for versions >= 3.17.0

README.md, defaults/main.yml, tasks/nexus_install.yml, templates/backup.groovy.j2
Fixes #226 (implementation)
Fixes #228 
Originally I had wanted to make this role support s3fs, but because there's a lot of ways this can be made to work, I think it's best to just leave the mounting/s3fs setup stuff to the developer instead of the role. The configuration for it is simple as well (see https://github.com/ansible-ThoTeam/nexus3-oss/issues/226#issuecomment-568531393 for my example using an amazon ami). Additionally, creating logic (tests in particular) for checking S3 permissions will probably complicate stuff.
If someone wants to take on the task of providing real S3 support, please do. But as for now, I think this PR should make it viable to set up s3fs outside of this role and not need to worry about it failing just because it can't create a directory with 0777 …
=> Adding configuration for creating backup directory or not + fixing backup script

templates/backup.groovy.j2
Week-based-year is probably not what people expect here and could easily trip up scripts trying to extract dates from the backup names.
=> Use normal year instead of week-based-year for backup names

README.md, tasks/main.yml
... for performance sake on installs containing large blobstores
=> Turn off recursive ownership check of blobstores dirs by default

tasks/main.yml, templates/nexus-blob-restore.sh.j2
Collateral damage of #241. When split blobstores is on
blobstore list was not valorised early enough
and blobstore restore script was buggy.
=> Fix blobstore restore script when splitted blobstore is on

.travis.yml, README.md, meta/main.yml, molecule/default-centos7/molecule.yml, molecule/default-centos8/converge.yml, molecule/default-centos8/molecule.yml, molecule/default-centos8/prepare.yml, molecule/default-centos8/tests/test_default.py, molecule/sync-nexus-package.yml
* CI now uses python 3.8
* New centos8 scenario
* All scenarios are kept but only latest platform
versions are tested on CI.
* Minor typos fix on prepare playbook task names
=> Maintenance for CI process

.ansible-lint, tasks/httpd_reverse_proxy_config.yml, tasks/nexus_install.yml
There is security issue [CVE-2020-1736](https://nvd.nist.gov/vuln/detail/CVE-2020-1736) about file permissions in Ansible modules. There was straight forward attempt to fix it, but it ended breaking a lot of modules and was reverted (more at https://github.com/ansible/ansible/issues/71200). So I've explicitly added `mode` option to the role tasks to support any further changes in Ansible.
Also added `ansible-lint` rule [106:  Role name {} does not match ``^[a-z][a-z0-9_]+$`` pattern](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#role-name-does-not-match-a-z-a-z0-9-pattern) to skip-list.
Fixes https://github.com/ansible-ThoTeam/nexus3-oss/issues/302
PR https://github.com/ansible-ThoTeam/nexus3-oss/pull/303 has been already merged into this PR.
=> Add explicit file permissions to tasks

tasks/nexus_install.yml
Fix checking if the data directory is empty for external drives with created only partition.
Fixes #279
=> Ignore lost+found while checking if data directory is empty

tasks/requirements_and_deprecated.yml
There is a small typo error **on line 59** of file below on first occurence of  **`public_hosname`**  in `when` condition of task : 
`name: Variable refactoring - public_hostname is now nexus_public_hostname`
=> fix typo in check of deprecated variable public_hostname

files/groovy/create_repos_from_list.groovy
Passing docker port as a string in the cofiguration works.
But it later breaks calls to the the /v1/repositories/docker/* api endpoints.
For example, asking for the current config of an existing repository
will return default ports instead of the current configured port.
This PR forces to push the port as an int inside the configuration to fix this issue
Fixes #262
=> Enforce docker http port number as Integer

README.md, defaults/main.yml, molecule/nexus_common_test_vars.yml, tasks/call_script.yml, tasks/declare_script_each.yml
Some groovy scripts, especially when provisioning from scratch with large number of objects, can take longer that the default timeout of the `uri` module (30s) to complete.
This PR introduces a new `nexus_api_timeout` parameter and raises the default timeout for API calls from 30 to 60 seconds.
Fixes #325
=> Allow to configure api calls timeout

README.md, defaults/main.yml, handlers/main.yml, tasks/nexus_install.yml
This PR adds a retry to the download of the Nexus package.
We currently use this role to install Nexus. However, we also use an existing Nexus which serves as a proxy for the Nexus packages. When downloading a newer version that is not yet available, the installation can fail because of a timeout when the new artifact is still downloading (with a slower internet connection, this is a common issue we have). Adding a retry is a solution for this issue.
Current behavior isn't changed because of the introduction of two new variables (which are also documented in the readme)
```yaml
nexus_download_retries: 3 # 0 by default
nexus_download_delay: 15
```
=> Feature: Add retries to download

.pre-commit-config.yaml, .yamllint, README.md, defaults/main.yml, handlers/main.yml, molecule/default-centos7/molecule.yml, molecule/default-centos8/molecule.yml, molecule/default-debian_bullseye/molecule.yml, molecule/default-debian_buster/molecule.yml, molecule/default-ubuntu_20.04/molecule.yml, molecule/default-ubuntu_22.04/molecule.yml, molecule/default/molecule.yml, molecule/nexus_common_test_vars.yml, molecule/nexus_ldap_test_vars.yml, requirements.txt, tasks/call_script.yml, tasks/declare_script_each.yml, tasks/httpd_reverse_proxy_config.yml, tasks/main.yml, tasks/nexus-restore.yml, tasks/nexus_install.yml, tasks/nexus_purge.yml, tasks/process_repos_list.yml, tasks/requirements_and_deprecated.yml, tasks/selinux-Debian.yml, tasks/selinux-RedHat.yml, vars/blob_vars.yml, vars/configure-Debian.yml, vars/configure-RedHat.yml
- change yamlint implementation
- allow ansible-lint to rewrite files
- some other hooks added
=> Linting enhancement:

files/groovy/create_repos_from_list.groovy, molecule/nexus_common_test_vars.yml
fixes #290
Looked like a simple change. Worked as expected on rockylinux9 during local dev/test cycle.
=> Enable provisioning offline repositories closes #290

README.md, defaults/main.yml, tasks/nexus_install.yml
Users on shared systems can encounter permission and/or concurrency
problems when groovy script are archived locally. This PR allows such
users to change the archive directory to a personnal tmp dir
rather that the system /tmp to avoid those issues.
Fixes #342
=> Fix archive scripts permission and concurrency problems

README.md, tasks/nexus_install.yml
I am migrating en existing nexus, and want to be able to set uid and gid to match my storage uid and gid. That is why this small change would be very helpful to have in here
=> Added Support for custom UID and GID for nexus user/group
